window.levels = {

      1: { words: ["coffee", "easy", "just"], translations: ["קפה", "קל", "רק"], guessedWords: new Set(), completed: false },
  2: { words: ["live", "hundred", "sorry"], translations: ["לחיות", "מאה", "מצטער"], guessedWords: new Set(), completed: false },
  3: { words: ["coffee", "easy", "just", "live", "hundred", "sorry"], translations: ["קפה", "קל", "רק", "לחיות", "מאה", "מצטער"], guessedWords: new Set(), completed: false },
  4: { words: ["there", "rest", "other"], translations: ["שם", "נותר", "אחר"], guessedWords: new Set(), completed: false },
  5: { words: ["fine", "money", "little"], translations: ["יופי", "כסף", "קטן"], guessedWords: new Set(), completed: false },
  6: { words: ["coffee", "easy", "just", "live", "hundred", "sorry", "there", "rest", "other", "fine", "money", "little"], translations: ["קפה", "קל", "רק", "לחיות", "מאה", "מצטער", "שם", "נותר", "אחר", "יופי", "כסף", "קטן"], guessedWords: new Set(), completed: false },
  7: { words: ["year", "right", "plan", "some"], translations: ["שנה", "נכון", "תוכנית", "כמה"], guessedWords: new Set(), completed: false },
  8: { words: ["round", "change", "page", "mouth"], translations: ["עגול", "שינוי", "דף", "פה"], guessedWords: new Set(), completed: false },
  9: { words: ["coffee", "easy", "just", "live", "hundred", "sorry", "there", "rest", "other", "fine", "money", "little", "year", "right", "plan", "some"], translations: ["קפה", "קל", "רק", "לחיות", "מאה", "מצטער", "שם", "נותר", "אחר", "יופי", "כסף", "קטן", "שנה", "נכון", "תוכנית", "כמה"], guessedWords: new Set(), completed: false },
  10: { words: ["please", "big", "have", "notebook", "see"], translations: ["בבקשה", "גדול", "יש", "מחברת", "לראות"], guessedWords: new Set(), completed: false },
  11: { words: ["break", "action", "bring", "going", "thank"], translations: ["לשבור", "פעולה", "להביא", "ללכת", "תודה"], guessedWords: new Set(), completed: false },
  12: { words: ["coffee", "easy", "just", "live", "hundred", "sorry", "there", "rest", "other", "fine", "money", "little", "year", "right", "plan", "some", "please", "big", "have", "notebook", "see", "break", "action", "bring", "going", "thank"], translations: ["קפה", "קל", "רק", "לחיות", "מאה", "מצטער", "שם", "נותר", "אחר", "יופי", "כסף", "קטן", "שנה", "נכון", "תוכנית", "כמה", "בבקשה", "גדול", "יש", "מחברת", "לראות", "לשבור", "פעולה", "להביא", "ללכת", "תודה"], guessedWords: new Set(), completed: false },
  13: { words: ["same", "love", "look", "example", "smart", "sing"], translations: ["אותו", "אהבה", "מראה", "דוגמה", "חכם", "לשיר"], guessedWords: new Set(), completed: false },
  14: { words: ["play", "dictionary", "full", "favorite", "window", "family"], translations: ["לשחק", "מילון", "מלא", "אהוב", "חלון", "משפחה"], guessedWords: new Set(), completed: false },
  15: { words: ["son", "hour", "same", "love", "look", "example", "smart", "sing", "play", "dictionary", "full", "favorite", "window", "family"], translations: ["בן", "שעה", "אותו", "אהבה", "מראה", "דוגמה", "חכם", "לשיר", "לשחק", "מילון", "מלא", "אהוב", "חלון", "משפחה"], guessedWords: new Set(), completed: false },
  16: { words: ["son", "hour", "same", "love", "look", "example", "smart", "sing", "play", "dictionary", "full", "favorite", "window", "family", "coffee", "easy", "just", "live", "hundred", "sorry", "there", "rest", "other", "fine", "money", "little", "year", "right", "plan", "some", "please", "big", "have", "notebook", "see", "break", "action", "bring", "going", "thank"], translations: ["בן", "שעה", "אותו", "אהבה", "מראה", "דוגמה", "חכם", "לשיר", "לשחק", "מילון", "מלא", "אהוב", "חלון", "משפחה", "קפה", "קל", "רק", "לחיות", "מאה", "מצטער", "שם", "נותר", "אחר", "יופי", "כסף", "קטן", "שנה", "נכון", "תוכנית", "כמה", "בבקשה", "גדול", "יש", "מחברת", "לראות", "לשבור", "פעולה", "להביא", "ללכת", "תודה"], guessedWords: new Set(), completed: false },
  17: { words: ["קפה", "קל", "רק", "לחיות", "מאה", "מצטער", "שם", "נותר", "אחר", "יופי"], translations: ["coffee", "easy", "just", "live", "hundred", "sorry", "there", "rest", "other", "fine"], guessedWords: new Set(), completed: false },
  18: { words: ["כסף", "קטן", "שנה", "נכון", "תוכנית", "כמה", "בבקשה", "גדול", "יש", "מחברת"], translations: ["money", "little", "year", "right", "plan", "some", "please", "big", "have", "notebook"], guessedWords: new Set(), completed: false },
  19: { words: ["לראות", "לשבור", "פעולה", "להביא", "ללכת", "תודה", "אותו", "אהבה", "מראה", "דוגמה"], translations: ["see", "break", "action", "bring", "going", "thank", "same", "love", "look", "example"], guessedWords: new Set(), completed: false },
  20: { words: ["חכם", "לשיר", "לשחק", "מילון", "מלא", "אהוב", "חלון", "משפחה", "בן", "שעה"], translations: ["smart", "sing", "play", "dictionary", "full", "favorite", "window", "family", "son", "hour"], guessedWords: new Set(), completed: false }
      
    };